version: '3' # Don't touch this

services: # Don't touch this
#    highlands_mongodb: # Don't touch this
#      container_name: $MONGO_NAME # Don't touch this
#      image: mongo # Don't touch this
#      restart: always
#      environment: # Don't touch this
#        MONGO_INITDB_ROOT_USERNAME: $MONGO_USER # Don't touch this
#        MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS # Don't touch this
#      volumes:
#          - mdb1:/data/db
#          - mdb2:/data/configdb
#      networks:
#          - highlands
#      ports: # Don't touch this
#          - $MONGO_PORT:27017 # Don't touch this
    highlands_web:
        restart: unless-stopped
        build: # Don't touch this
            dockerfile: Dockerfile # Don't touch this
            context: ./Dockerfiles/ # Don't touch this
        container_name: $WEB_NAME # Specify the container name
        tty: true # Don't touch this
        networks:
            - highlands
        volumes:
            - ./app:/app # Don't touch this
            - hl1:/var/lib/zerotier-one
        ports:
            - $WEB_PORT:5000 # Port '5000' is the Flask Applications webserver port
        cap_add:
            - NET_ADMIN

volumes:
    hl1:
    mdb1:
    mdb2:

networks:
    highlands:
        external: true
