version: '3' # Don't touch this

services: # Don't touch this
    highlands_web:
        restart: unless-stopped
        build: # Don't touch this
            dockerfile: Dockerfile # Don't touch this
            context: ./Dockerfiles/ # Don't touch this
        container_name: $HTTP_NAME # Specify the container name
        tty: true # Don't touch this
        volumes:
            - ./app:/app # Don't touch this
            - zt1:/var/lib/zerotier-one
        ports:
            - $HTTP_PORT:5000 # Port '5000' is the Flask Applications webserver port
        cap_add:
            - NET_ADMIN

volumes:
    zt1:
